///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsImagesLogo = 'assets/images/logo-bleu.png';
  static const String newtgtAssetsAirlines = 'assets/airlines.json';
  static const String imagesLogoWhite = 'assets/images/logo-white.png';
  static const String chatbotbutton = 'assets/images/chatbotbutton.png';

  static const String robot = 'assets/robot.png';
  static const String robotd = 'assets/robotd.png';
}
